In [233]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score, LeaveOneOut
from sklearn import svm
from sklearn.linear_model import LinearRegression, LogisticRegression, PassiveAggressiveClassifier

In [234]:
cor =  """United States	612380	538395	25949	48036
Spain	174060	88301	18255	67504
Italy	162488	104291	21067	37130
Germany	132210	70603	3495	58112
France	103573	59039	15729	28805
United Kingdom	93873	81558	12107	208
China	82052	1138	3339	77575
Iran	74877	22065	4683	48129
Turkey	65111	58909	1403	4799
Belgium	31119	20094	4157	6868
Netherlands	27419	24474	2945	0
Canada	27063	17925	903	8235
Switzerland	25936	10062	1174	14700
Brazil	25262	9704	1532	14026
Russia	21102	19238	170	1694
Portugal	17448	16534	567	347
Austria	14234	6217	384	7633
Georgia	14223	13950	501	69
Israel	12046	9728	123	2195
Ireland	11479	11048	406	25
Sweden	11445	10039	1033	373
India	10815	9272	353	1190
South Korea	10591	2750	225	7616
Peru	10303	7204	230	2869
Chile	7917	5179	92	2646
Japan	7645	6683	109	853
Ecuador	7603	6552	355	696
Poland	7202	6321	263	618
Romania	6879	5482	346	1051
Norway	6686	6547	139	0
Denmark	6511	3697	299	2515
Australia	6400	2741	61	3598
Czech Republic	6111	5308	161	642
Pakistan	5837	4363	96	1378
Saudi Arabia	5369	4407	73	889
Philippines	5223	4593	335	295
Mexico	5014	2718	332	1964
Malaysia	4987	2427	82	2478
United Arab Emirates	4933	3972	28	933
Indonesia	4839	3954	459	426
Serbia	4465	3971	94	400
Panama	3574	3407	95	72
Qatar	3428	3048	7	373
Ukraine	3372	3155	98	119
Luxembourg	3307	2752	69	486
Dominican Republic	3286	2941	183	162
Belarus	3281	3045	33	203
Singapore	3252	2631	10	611
Finland	3161	2236	59	866
Colombia	2979	2498	127	354
Thailand	2613	1167	41	1405
South Africa	2415	1978	27	410
Egypt	2350	1583	178	589
Argentina	2277	1617	101	559
Greece	2170	1800	101	269
Algeria	2070	1053	326	691
Moldova	1934	1762	38	134
Morocco	1888	1545	126	217
Iceland	1720	723	8	989
Croatia	1704	1258	31	415
Bahrain	1528	876	7	645
Hungary	1512	1268	122	122
Iraq	1400	556	78	766
Estonia	1373	1227	31	115
Kuwait	1355	1203	2	150
Kazakhstan	1232	1015	14	203
Slovenia	1220	1012	56	152
Azerbaijan	1197	833	13	351
Uzbekistan	1165	1062	4	99
New Zealand	1078	341	9	728
Lithuania	1070	945	24	101
Armenia	1067	786	16	265
Hong Kong	1013	575	4	434
Bangladesh	1012	924	46	42
Puerto Rico	923	1756	45	0
North Macedonia	908	778	44	86
Cameroon	848	704	14	130
Slovakia	835	726	2	107
Oman	813	679	4	130
Cuba	766	613	21	132
Tunisia	747	670	34	43
Afghanistan	714	651	23	40
Bulgaria	713	597	35	81
Others	712	81	12	619
Cyprus	685	608	12	65
Andorra	659	468	31	160
Latvia	657	636	5	16
Lebanon	641	540	21	80
Ivory Coast	638	518	6	114
Ghana	636	611	8	17
Costa Rica	618	549	3	66
Niger	570	466	14	90
Burkina Faso	528	321	30	177
Uruguay	492	224	8	260
Albania	475	203	24	248
Kyrgyzstan	430	354	5	71
Honduras	407	374	26	7
Jordan	397	155	7	235
Malta	393	346	3	44
Taiwan	393	263	6	124
Réunion	391	351	0	40
Kosovo	387	313	8	66
Nigeria	373	263	11	99
San Marino	372	283	36	53
Guinea	363	332	0	31
Bolivia	354	320	28	6
Mauritius	324	264	9	51
Senegal	299	114	2	183
Palestine	288	224	2	62
Montenegro	283	276	2	5
Vietnam	266	97	0	169
Djibouti	263	208	2	53
Isle Of Man	254	111	2	141
DR Congo	241	201	20	20
Sri Lanka	233	165	7	61
Guernsey	223	163	7	53
Mayotte	217	145	3	69
Jersey	217	211	6	0
Kenya	216	166	9	41
Venezuela	193	73	9	111
Faroe Islands	184	21	0	163
Guatemala	167	143	5	19
Paraguay	159	130	7	22
Martinique	157	99	8	50
El Salvador	149	118	6	25
Guadeloupe	145	70	8	67
Mali	144	105	13	26
Brunei	136	36	1	99
Rwanda	134	85	0	49
Guam	133	140	5	58
Gibraltar	129	39	0	90
Cambodia	122	31	0	91
Madagascar	106	86	0	20
Jamaica	105	82	4	19
Northern Cyprus	99	52	3	44
Monaco	93	86	1	6
Aruba	92	60	0	32
French Guiana	88	35	0	53
Ethiopia	82	65	3	14
Liechtenstein	79	23	1	55
Togo	77	42	3	32
Republic Of The Congo	74	59	5	10
Barbados	73	53	5	15
Myanmar	63	57	4	2
Somalia	60	56	2	2
Bermuda	57	22	5	30
Gabon	57	55	1	1
French Polynesia	55	55	0	0
Uganda	55	51	0	4
Cayman Islands	54	47	1	6
Tanzania	53	43	3	7
Sint Maarten	52	41	8	3
U.S. Virgin Islands	51	14	1	43
Liberia	50	42	5	3
Bahamas	49	35	8	6
Guyana	47	33	6	8
Zambia	45	13	2	30
Macau	45	32	0	13
Equatorial Guinea	41	37	0	4
Haiti	40	37	3	0
Guinea-Bissau	39	39	0	0
Libya	35	25	1	9
Eritrea	35	35	0	0
Benin	35	29	1	5
Saint Martin	33	17	3	13
Sudan	32	25	5	2
Mongolia	30	25	0	5
Syria	29	22	2	5
Mozambique	28	26	0	2
Chad	23	21	0	2
Maldives	20	4	0	16
Laos	19	19	0	0
Angola	19	15	2	2
Donetsk PR	18	18	0	0
New Caledonia	18	8	0	10
Belize	18	16	2	0
Zimbabwe	17	14	3	0
Dominica	16	11	0	5
Malawi	16	14	2	0
Fiji	16	16	0	0
Namibia	16	14	0	2
Nepal	16	15	0	1
Eswatini	15	8	0	7
Saint Lucia	15	15	0	0
Curaçao	14	6	1	7
Grenada	14	14	0	0
Botswana	13	12	1	0
Saint Vincent	12	11	0	1
Northern Mariana Islands	11	18	2	0
Central African Republic	11	8	0	3
Falkland Islands	11	10	0	1
Sierra Leone	11	11	0	0
Montserrat	11	10	0	1
Greenland	11	0	0	11
Cape Verde	11	10	1	0
Nicaragua	11	6	1	4
Seychelles	11	11	0	0
Akrotiri	10	10	0	0
Åland Islands	10	10	0	0
Suriname	10	3	1	6
Gambia	9	6	1	2
Luhansk PR	8	7	0	1
Vatican City	8	6	0	2
Mauritania	7	4	1	2
Saint Barthélemy	6	5	0	1
East Timor	6	5	0	1
Artsakh	5	5	0	0
Burundi	5	4	1	0
Bhutan	5	3	0	2
São Tomé	4	4	0	0
South Sudan	4	4	0	0
British Virgin Islands	3	3	0	0
Anguilla	3	3	0	0
Saba	2	2	0	0
Sint Eustatius	2	2	0	0
Somaliland	2	2	0	0
Papua New Guinea	2	2	0	0
Yemen	1	1	0	0
Abkhazia	1	1	0	0
Guantanamo Bay	1	1	0	0"""

In [235]:
cor = cor.replace("	", " ")
cor = cor.split("\n")
cor

['United States 612380 538395 25949 48036',
 'Spain 174060 88301 18255 67504',
 'Italy 162488 104291 21067 37130',
 'Germany 132210 70603 3495 58112',
 'France 103573 59039 15729 28805',
 'United Kingdom 93873 81558 12107 208',
 'China 82052 1138 3339 77575',
 'Iran 74877 22065 4683 48129',
 'Turkey 65111 58909 1403 4799',
 'Belgium 31119 20094 4157 6868',
 'Netherlands 27419 24474 2945 0',
 'Canada 27063 17925 903 8235',
 'Switzerland 25936 10062 1174 14700',
 'Brazil 25262 9704 1532 14026',
 'Russia 21102 19238 170 1694',
 'Portugal 17448 16534 567 347',
 'Austria 14234 6217 384 7633',
 'Georgia 14223 13950 501 69',
 'Israel 12046 9728 123 2195',
 'Ireland 11479 11048 406 25',
 'Sweden 11445 10039 1033 373',
 'India 10815 9272 353 1190',
 'South Korea 10591 2750 225 7616',
 'Peru 10303 7204 230 2869',
 'Chile 7917 5179 92 2646',
 'Japan 7645 6683 109 853',
 'Ecuador 7603 6552 355 696',
 'Poland 7202 6321 263 618',
 'Romania 6879 5482 346 1051',
 'Norway 6686 6547 139 0',
 'Denmark 6511 3697 299 2515',
 'Australia 6400 2741 61 3598',
 'Czech Republic 6111 5308 161 642',
 'Pakistan 5837 4363 96 1378',
 'Saudi Arabia 5369 4407 73 889',
 'Philippines 5223 4593 335 295',
 'Mexico 5014 2718 332 1964',
 'Malaysia 4987 2427 82 2478',
 'United Arab Emirates 4933 3972 28 933',
 'Indonesia 4839 3954 459 426',
 'Serbia 4465 3971 94 400',
 'Panama 3574 3407 95 72',
 'Qatar 3428 3048 7 373',
 'Ukraine 3372 3155 98 119',
 'Luxembourg 3307 2752 69 486',
 'Dominican Republic 3286 2941 183 162',
 'Belarus 3281 3045 33 203',
 'Singapore 3252 2631 10 611',
 'Finland 3161 2236 59 866',
 'Colombia 2979 2498 127 354',
 'Thailand 2613 1167 41 1405',
 'South Africa 2415 1978 27 410',
 'Egypt 2350 1583 178 589',
 'Argentina 2277 1617 101 559',
 'Greece 2170 1800 101 269',
 'Algeria 2070 1053 326 691',
 'Moldova 1934 1762 38 134',
 'Morocco 1888 1545 126 217',
 'Iceland 1720 723 8 989',
 'Croatia 1704 1258 31 415',
 'Bahrain 1528 876 7 645',
 'Hungary 1512 1268 122 122',
 'Iraq 1400 556 78 766',
 'Estonia 1373 1227 31 115',
 'Kuwait 1355 1203 2 150',
 'Kazakhstan 1232 1015 14 203',
 'Slovenia 1220 1012 56 152',
 'Azerbaijan 1197 833 13 351',
 'Uzbekistan 1165 1062 4 99',
 'New Zealand 1078 341 9 728',
 'Lithuania 1070 945 24 101',
 'Armenia 1067 786 16 265',
 'Hong Kong 1013 575 4 434',
 'Bangladesh 1012 924 46 42',
 'Puerto Rico 923 1756 45 0',
 'North Macedonia 908 778 44 86',
 'Cameroon 848 704 14 130',
 'Slovakia 835 726 2 107',
 'Oman 813 679 4 130',
 'Cuba 766 613 21 132',
 'Tunisia 747 670 34 43',
 'Afghanistan 714 651 23 40',
 'Bulgaria 713 597 35 81',
 'Others 712 81 12 619',
 'Cyprus 685 608 12 65',
 'Andorra 659 468 31 160',
 'Latvia 657 636 5 16',
 'Lebanon 641 540 21 80',
 'Ivory Coast 638 518 6 114',
 'Ghana 636 611 8 17',
 'Costa Rica 618 549 3 66',
 'Niger 570 466 14 90',
 'Burkina Faso 528 321 30 177',
 'Uruguay 492 224 8 260',
 'Albania 475 203 24 248',
 'Kyrgyzstan 430 354 5 71',
 'Honduras 407 374 26 7',
 'Jordan 397 155 7 235',
 'Malta 393 346 3 44',
 'Taiwan 393 263 6 124',
 'Réunion 391 351 0 40',
 'Kosovo 387 313 8 66',
 'Nigeria 373 263 11 99',
 'San Marino 372 283 36 53',
 'Guinea 363 332 0 31',
 'Bolivia 354 320 28 6',
 'Mauritius 324 264 9 51',
 'Senegal 299 114 2 183',
 'Palestine 288 224 2 62',
 'Montenegro 283 276 2 5',
 'Vietnam 266 97 0 169',
 'Djibouti 263 208 2 53',
 'Isle Of Man 254 111 2 141',
 'DR Congo 241 201 20 20',
 'Sri Lanka 233 165 7 61',
 'Guernsey 223 163 7 53',
 'Mayotte 217 145 3 69',
 'Jersey 217 211 6 0',
 'Kenya 216 166 9 41',
 'Venezuela 193 73 9 111',
 'Faroe Islands 184 21 0 163',
 'Guatemala 167 143 5 19',
 'Paraguay 159 130 7 22',
 'Martinique 157 99 8 50',
 'El Salvador 149 118 6 25',
 'Guadeloupe 145 70 8 67',
 'Mali 144 105 13 26',
 'Brunei 136 36 1 99',
 'Rwanda 134 85 0 49',
 'Guam 133 140 5 58',
 'Gibraltar 129 39 0 90',
 'Cambodia 122 31 0 91',
 'Madagascar 106 86 0 20',
 'Jamaica 105 82 4 19',
 'Northern Cyprus 99 52 3 44',
 'Monaco 93 86 1 6',
 'Aruba 92 60 0 32',
 'French Guiana 88 35 0 53',
 'Ethiopia 82 65 3 14',
 'Liechtenstein 79 23 1 55',
 'Togo 77 42 3 32',
 'Republic Of The Congo 74 59 5 10',
 'Barbados 73 53 5 15',
 'Myanmar 63 57 4 2',
 'Somalia 60 56 2 2',
 'Bermuda 57 22 5 30',
 'Gabon 57 55 1 1',
 'French Polynesia 55 55 0 0',
 'Uganda 55 51 0 4',
 'Cayman Islands 54 47 1 6',
 'Tanzania 53 43 3 7',
 'Sint Maarten 52 41 8 3',
 'U.S. Virgin Islands 51 14 1 43',
 'Liberia 50 42 5 3',
 'Bahamas 49 35 8 6',
 'Guyana 47 33 6 8',
 'Zambia 45 13 2 30',
 'Macau 45 32 0 13',
 'Equatorial Guinea 41 37 0 4',
 'Haiti 40 37 3 0',
 'Guinea-Bissau 39 39 0 0',
 'Libya 35 25 1 9',
 'Eritrea 35 35 0 0',
 'Benin 35 29 1 5',
 'Saint Martin 33 17 3 13',
 'Sudan 32 25 5 2',
 'Mongolia 30 25 0 5',
 'Syria 29 22 2 5',
 'Mozambique 28 26 0 2',
 'Chad 23 21 0 2',
 'Maldives 20 4 0 16',
 'Laos 19 19 0 0',
 'Angola 19 15 2 2',
 'Donetsk PR 18 18 0 0',
 'New Caledonia 18 8 0 10',
 'Belize 18 16 2 0',
 'Zimbabwe 17 14 3 0',
 'Dominica 16 11 0 5',
 'Malawi 16 14 2 0',
 'Fiji 16 16 0 0',
 'Namibia 16 14 0 2',
 'Nepal 16 15 0 1',
 'Eswatini 15 8 0 7',
 'Saint Lucia 15 15 0 0',
 'Curaçao 14 6 1 7',
 'Grenada 14 14 0 0',
 'Botswana 13 12 1 0',
 'Saint Vincent 12 11 0 1',
 'Northern Mariana Islands 11 18 2 0',
 'Central African Republic 11 8 0 3',
 'Falkland Islands 11 10 0 1',
 'Sierra Leone 11 11 0 0',
 'Montserrat 11 10 0 1',
 'Greenland 11 0 0 11',
 'Cape Verde 11 10 1 0',
 'Nicaragua 11 6 1 4',
 'Seychelles 11 11 0 0',
 'Akrotiri 10 10 0 0',
 'Åland Islands 10 10 0 0',
 'Suriname 10 3 1 6',
 'Gambia 9 6 1 2',
 'Luhansk PR 8 7 0 1',
 'Vatican City 8 6 0 2',
 'Mauritania 7 4 1 2',
 'Saint Barthélemy 6 5 0 1',
 'East Timor 6 5 0 1',
 'Artsakh 5 5 0 0',
 'Burundi 5 4 1 0',
 'Bhutan 5 3 0 2',
 'São Tomé 4 4 0 0',
 'South Sudan 4 4 0 0',
 'British Virgin Islands 3 3 0 0',
 'Anguilla 3 3 0 0',
 'Saba 2 2 0 0',
 'Sint Eustatius 2 2 0 0',
 'Somaliland 2 2 0 0',
 'Papua New Guinea 2 2 0 0',
 'Yemen 1 1 0 0',
 'Abkhazia 1 1 0 0',
 'Guantanamo Bay 1 1 0 0']

In [236]:
cor = list(map(lambda x: x.split(" "), cor))

In [237]:
cor

[['United', 'States', '612380', '538395', '25949', '48036'],
 ['Spain', '174060', '88301', '18255', '67504'],
 ['Italy', '162488', '104291', '21067', '37130'],
 ['Germany', '132210', '70603', '3495', '58112'],
 ['France', '103573', '59039', '15729', '28805'],
 ['United', 'Kingdom', '93873', '81558', '12107', '208'],
 ['China', '82052', '1138', '3339', '77575'],
 ['Iran', '74877', '22065', '4683', '48129'],
 ['Turkey', '65111', '58909', '1403', '4799'],
 ['Belgium', '31119', '20094', '4157', '6868'],
 ['Netherlands', '27419', '24474', '2945', '0'],
 ['Canada', '27063', '17925', '903', '8235'],
 ['Switzerland', '25936', '10062', '1174', '14700'],
 ['Brazil', '25262', '9704', '1532', '14026'],
 ['Russia', '21102', '19238', '170', '1694'],
 ['Portugal', '17448', '16534', '567', '347'],
 ['Austria', '14234', '6217', '384', '7633'],
 ['Georgia', '14223', '13950', '501', '69'],
 ['Israel', '12046', '9728', '123', '2195'],
 ['Ireland', '11479', '11048', '406', '25'],
 ['Sweden', '11445', '10039', '1033', '373'],
 ['India', '10815', '9272', '353', '1190'],
 ['South', 'Korea', '10591', '2750', '225', '7616'],
 ['Peru', '10303', '7204', '230', '2869'],
 ['Chile', '7917', '5179', '92', '2646'],
 ['Japan', '7645', '6683', '109', '853'],
 ['Ecuador', '7603', '6552', '355', '696'],
 ['Poland', '7202', '6321', '263', '618'],
 ['Romania', '6879', '5482', '346', '1051'],
 ['Norway', '6686', '6547', '139', '0'],
 ['Denmark', '6511', '3697', '299', '2515'],
 ['Australia', '6400', '2741', '61', '3598'],
 ['Czech', 'Republic', '6111', '5308', '161', '642'],
 ['Pakistan', '5837', '4363', '96', '1378'],
 ['Saudi', 'Arabia', '5369', '4407', '73', '889'],
 ['Philippines', '5223', '4593', '335', '295'],
 ['Mexico', '5014', '2718', '332', '1964'],
 ['Malaysia', '4987', '2427', '82', '2478'],
 ['United', 'Arab', 'Emirates', '4933', '3972', '28', '933'],
 ['Indonesia', '4839', '3954', '459', '426'],
 ['Serbia', '4465', '3971', '94', '400'],
 ['Panama', '3574', '3407', '95', '72'],
 ['Qatar', '3428', '3048', '7', '373'],
 ['Ukraine', '3372', '3155', '98', '119'],
 ['Luxembourg', '3307', '2752', '69', '486'],
 ['Dominican', 'Republic', '3286', '2941', '183', '162'],
 ['Belarus', '3281', '3045', '33', '203'],
 ['Singapore', '3252', '2631', '10', '611'],
 ['Finland', '3161', '2236', '59', '866'],
 ['Colombia', '2979', '2498', '127', '354'],
 ['Thailand', '2613', '1167', '41', '1405'],
 ['South', 'Africa', '2415', '1978', '27', '410'],
 ['Egypt', '2350', '1583', '178', '589'],
 ['Argentina', '2277', '1617', '101', '559'],
 ['Greece', '2170', '1800', '101', '269'],
 ['Algeria', '2070', '1053', '326', '691'],
 ['Moldova', '1934', '1762', '38', '134'],
 ['Morocco', '1888', '1545', '126', '217'],
 ['Iceland', '1720', '723', '8', '989'],
 ['Croatia', '1704', '1258', '31', '415'],
 ['Bahrain', '1528', '876', '7', '645'],
 ['Hungary', '1512', '1268', '122', '122'],
 ['Iraq', '1400', '556', '78', '766'],
 ['Estonia', '1373', '1227', '31', '115'],
 ['Kuwait', '1355', '1203', '2', '150'],
 ['Kazakhstan', '1232', '1015', '14', '203'],
 ['Slovenia', '1220', '1012', '56', '152'],
 ['Azerbaijan', '1197', '833', '13', '351'],
 ['Uzbekistan', '1165', '1062', '4', '99'],
 ['New', 'Zealand', '1078', '341', '9', '728'],
 ['Lithuania', '1070', '945', '24', '101'],
 ['Armenia', '1067', '786', '16', '265'],
 ['Hong', 'Kong', '1013', '575', '4', '434'],
 ['Bangladesh', '1012', '924', '46', '42'],
 ['Puerto', 'Rico', '923', '1756', '45', '0'],
 ['North', 'Macedonia', '908', '778', '44', '86'],
 ['Cameroon', '848', '704', '14', '130'],
 ['Slovakia', '835', '726', '2', '107'],
 ['Oman', '813', '679', '4', '130'],
 ['Cuba', '766', '613', '21', '132'],
 ['Tunisia', '747', '670', '34', '43'],
 ['Afghanistan', '714', '651', '23', '40'],
 ['Bulgaria', '713', '597', '35', '81'],
 ['Others', '712', '81', '12', '619'],
 ['Cyprus', '685', '608', '12', '65'],
 ['Andorra', '659', '468', '31', '160'],
 ['Latvia', '657', '636', '5', '16'],
 ['Lebanon', '641', '540', '21', '80'],
 ['Ivory', 'Coast', '638', '518', '6', '114'],
 ['Ghana', '636', '611', '8', '17'],
 ['Costa', 'Rica', '618', '549', '3', '66'],
 ['Niger', '570', '466', '14', '90'],
 ['Burkina', 'Faso', '528', '321', '30', '177'],
 ['Uruguay', '492', '224', '8', '260'],
 ['Albania', '475', '203', '24', '248'],
 ['Kyrgyzstan', '430', '354', '5', '71'],
 ['Honduras', '407', '374', '26', '7'],
 ['Jordan', '397', '155', '7', '235'],
 ['Malta', '393', '346', '3', '44'],
 ['Taiwan', '393', '263', '6', '124'],
 ['Réunion', '391', '351', '0', '40'],
 ['Kosovo', '387', '313', '8', '66'],
 ['Nigeria', '373', '263', '11', '99'],
 ['San', 'Marino', '372', '283', '36', '53'],
 ['Guinea', '363', '332', '0', '31'],
 ['Bolivia', '354', '320', '28', '6'],
 ['Mauritius', '324', '264', '9', '51'],
 ['Senegal', '299', '114', '2', '183'],
 ['Palestine', '288', '224', '2', '62'],
 ['Montenegro', '283', '276', '2', '5'],
 ['Vietnam', '266', '97', '0', '169'],
 ['Djibouti', '263', '208', '2', '53'],
 ['Isle', 'Of', 'Man', '254', '111', '2', '141'],
 ['DR', 'Congo', '241', '201', '20', '20'],
 ['Sri', 'Lanka', '233', '165', '7', '61'],
 ['Guernsey', '223', '163', '7', '53'],
 ['Mayotte', '217', '145', '3', '69'],
 ['Jersey', '217', '211', '6', '0'],
 ['Kenya', '216', '166', '9', '41'],
 ['Venezuela', '193', '73', '9', '111'],
 ['Faroe', 'Islands', '184', '21', '0', '163'],
 ['Guatemala', '167', '143', '5', '19'],
 ['Paraguay', '159', '130', '7', '22'],
 ['Martinique', '157', '99', '8', '50'],
 ['El', 'Salvador', '149', '118', '6', '25'],
 ['Guadeloupe', '145', '70', '8', '67'],
 ['Mali', '144', '105', '13', '26'],
 ['Brunei', '136', '36', '1', '99'],
 ['Rwanda', '134', '85', '0', '49'],
 ['Guam', '133', '140', '5', '58'],
 ['Gibraltar', '129', '39', '0', '90'],
 ['Cambodia', '122', '31', '0', '91'],
 ['Madagascar', '106', '86', '0', '20'],
 ['Jamaica', '105', '82', '4', '19'],
 ['Northern', 'Cyprus', '99', '52', '3', '44'],
 ['Monaco', '93', '86', '1', '6'],
 ['Aruba', '92', '60', '0', '32'],
 ['French', 'Guiana', '88', '35', '0', '53'],
 ['Ethiopia', '82', '65', '3', '14'],
 ['Liechtenstein', '79', '23', '1', '55'],
 ['Togo', '77', '42', '3', '32'],
 ['Republic', 'Of', 'The', 'Congo', '74', '59', '5', '10'],
 ['Barbados', '73', '53', '5', '15'],
 ['Myanmar', '63', '57', '4', '2'],
 ['Somalia', '60', '56', '2', '2'],
 ['Bermuda', '57', '22', '5', '30'],
 ['Gabon', '57', '55', '1', '1'],
 ['French', 'Polynesia', '55', '55', '0', '0'],
 ['Uganda', '55', '51', '0', '4'],
 ['Cayman', 'Islands', '54', '47', '1', '6'],
 ['Tanzania', '53', '43', '3', '7'],
 ['Sint', 'Maarten', '52', '41', '8', '3'],
 ['U.S.', 'Virgin', 'Islands', '51', '14', '1', '43'],
 ['Liberia', '50', '42', '5', '3'],
 ['Bahamas', '49', '35', '8', '6'],
 ['Guyana', '47', '33', '6', '8'],
 ['Zambia', '45', '13', '2', '30'],
 ['Macau', '45', '32', '0', '13'],
 ['Equatorial', 'Guinea', '41', '37', '0', '4'],
 ['Haiti', '40', '37', '3', '0'],
 ['Guinea-Bissau', '39', '39', '0', '0'],
 ['Libya', '35', '25', '1', '9'],
 ['Eritrea', '35', '35', '0', '0'],
 ['Benin', '35', '29', '1', '5'],
 ['Saint', 'Martin', '33', '17', '3', '13'],
 ['Sudan', '32', '25', '5', '2'],
 ['Mongolia', '30', '25', '0', '5'],
 ['Syria', '29', '22', '2', '5'],
 ['Mozambique', '28', '26', '0', '2'],
 ['Chad', '23', '21', '0', '2'],
 ['Maldives', '20', '4', '0', '16'],
 ['Laos', '19', '19', '0', '0'],
 ['Angola', '19', '15', '2', '2'],
 ['Donetsk', 'PR', '18', '18', '0', '0'],
 ['New', 'Caledonia', '18', '8', '0', '10'],
 ['Belize', '18', '16', '2', '0'],
 ['Zimbabwe', '17', '14', '3', '0'],
 ['Dominica', '16', '11', '0', '5'],
 ['Malawi', '16', '14', '2', '0'],
 ['Fiji', '16', '16', '0', '0'],
 ['Namibia', '16', '14', '0', '2'],
 ['Nepal', '16', '15', '0', '1'],
 ['Eswatini', '15', '8', '0', '7'],
 ['Saint', 'Lucia', '15', '15', '0', '0'],
 ['Curaçao', '14', '6', '1', '7'],
 ['Grenada', '14', '14', '0', '0'],
 ['Botswana', '13', '12', '1', '0'],
 ['Saint', 'Vincent', '12', '11', '0', '1'],
 ['Northern', 'Mariana', 'Islands', '11', '18', '2', '0'],
 ['Central', 'African', 'Republic', '11', '8', '0', '3'],
 ['Falkland', 'Islands', '11', '10', '0', '1'],
 ['Sierra', 'Leone', '11', '11', '0', '0'],
 ['Montserrat', '11', '10', '0', '1'],
 ['Greenland', '11', '0', '0', '11'],
 ['Cape', 'Verde', '11', '10', '1', '0'],
 ['Nicaragua', '11', '6', '1', '4'],
 ['Seychelles', '11', '11', '0', '0'],
 ['Akrotiri', '10', '10', '0', '0'],
 ['Åland', 'Islands', '10', '10', '0', '0'],
 ['Suriname', '10', '3', '1', '6'],
 ['Gambia', '9', '6', '1', '2'],
 ['Luhansk', 'PR', '8', '7', '0', '1'],
 ['Vatican', 'City', '8', '6', '0', '2'],
 ['Mauritania', '7', '4', '1', '2'],
 ['Saint', 'Barthélemy', '6', '5', '0', '1'],
 ['East', 'Timor', '6', '5', '0', '1'],
 ['Artsakh', '5', '5', '0', '0'],
 ['Burundi', '5', '4', '1', '0'],
 ['Bhutan', '5', '3', '0', '2'],
 ['São', 'Tomé', '4', '4', '0', '0'],
 ['South', 'Sudan', '4', '4', '0', '0'],
 ['British', 'Virgin', 'Islands', '3', '3', '0', '0'],
 ['Anguilla', '3', '3', '0', '0'],
 ['Saba', '2', '2', '0', '0'],
 ['Sint', 'Eustatius', '2', '2', '0', '0'],
 ['Somaliland', '2', '2', '0', '0'],
 ['Papua', 'New', 'Guinea', '2', '2', '0', '0'],
 ['Yemen', '1', '1', '0', '0'],
 ['Abkhazia', '1', '1', '0', '0'],
 ['Guantanamo', 'Bay', '1', '1', '0', '0']]

In [238]:
cor = np.array(list(map(lambda x: np.append(np.array(list(map(lambda y: int(y), x[-4:]))), (" ".join(x[:-4]))), cor)))
cor

array([['612380', '538395', '25949', '48036', 'United States'],
       ['174060', '88301', '18255', '67504', 'Spain'],
       ['162488', '104291', '21067', '37130', 'Italy'],
       ...,
       ['1', '1', '0', '0', 'Yemen'],
       ['1', '1', '0', '0', 'Abkhazia'],
       ['1', '1', '0', '0', 'Guantanamo Bay']], dtype='<U24')

In [239]:
cor.shape

(220, 5)

In [240]:
df = pd.DataFrame(cor, index=cor[0:, 4])

In [241]:
df = df.sort_values(by=[4])

In [242]:
df.drop(4, axis=1, inplace=True)

In [243]:
df.columns = ["total", "active", "deaths", "recovered"]

In [244]:
df

              total active deaths recovered
Abkhazia          1      1      0         0
Afghanistan     714    651     23        40
Akrotiri         10     10      0         0
Albania         475    203     24       248
Algeria        2070   1053    326       691
...             ...    ...    ...       ...
Vietnam         266     97      0       169
Yemen             1      1      0         0
Zambia           45     13      2        30
Zimbabwe         17     14      3         0
Åland Islands    10     10      0         0

[220 rows x 4 columns]

In [309]:
mort = pd.read_csv("./Datasets/mortality rate.csv", sep=";", index_col=0)
pop = pd.read_csv("./Datasets/pop.csv", sep=";", index_col=0)
med = pd.read_csv("./Datasets/med_age.csv", sep=";", index_col=0)#insufficient
#CREATE DF WITH ALL UN DATA AND THEN CONCAT

In [310]:
ind = list(map(lambda x: x in mort.index, df.index))
ind1 = list(map(lambda x: x in df.index, mort.index))

In [311]:
df.loc[ind].index

Index(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Anguilla',
       'Argentina', 'Armenia', 'Aruba', 'Australia',
       ...
       'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'Uruguay', 'Uzbekistan', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='object', length=172)

In [312]:
df.loc[ind].index == mort.loc[ind1].index

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [313]:
main_fraim = pd.concat([df.loc[ind], mort.loc[ind1], pop.loc[ind1]], axis=1)

In [314]:
main_fraim

            total active deaths recovered mortality_rate       pop
Afghanistan   714    651     23        40         38 928    38 928
Albania       475    203     24       248          2 878     2 878
Algeria      2070   1053    326       691         43 851    43 851
Andorra       659    468     31       160             77        77
Angola         19     15      2         2         32 866    32 866
...           ...    ...    ...       ...            ...       ...
Uruguay       492    224      8       260          3 474     3 474
Uzbekistan   1165   1062      4        99         33 469    33 469
Yemen           1      1      0         0         29 826    29 826
Zambia         45     13      2        30         18 384    18 384
Zimbabwe       17     14      3         0         14 863    14 863

[172 rows x 6 columns]